### ISSUE TITLE
bug:  allow websocket to restart

### ISSUE THREAD

**Issue by denopink** [xmidt-org/xmidt-agent#102]

**Comment by schmidtw** [comment]
For the agent, the websocket probably shouldn't be re-used.  The reason for this is the entire process, including if IPv4 or IPv6 is to be used must be re-evalutated to ensure that if there is a failure between the CPE and the cloud, all the random paths that are intentionally inserted will be honored.

**Comment by denopink** [comment]
i learned something new(!) and that makes sense, sounds good to me

closing
