### ISSUE TITLE
Refactor out the built-in configuration into a file so it can be more useful.

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/xmidt-agent#136]
Instead of building into the code the configuration, let's move it out to it's own yaml file `built-in.yml` that we use for the default built in values.

This helps us with a number of things:
- The configuration format used is the same folks will use in configuration files.
- More comments, examples and other annotations can be done.
- We can add a command line option that dumps out the built-in.yml file including all the comments so everyone can see/access it.

**Comment by piccione99** [comment]
complete
