### ISSUE TITLE
Add pub/sub wrp.Normify Options

### ISSUE THREAD

**Issue by denopink** [xmidt-org/xmidt-agent#93]

**Comment by schmidtw** [comment]
Can you provide more details about what you think needs to be added?

**Comment by denopink** [comment]
totally forgot we already added the wrp.Normify Options we wanted

https://github.com/xmidt-org/xmidt-agent/blob/c560fbe7e3f1b5138360a891957af2c4c0466456/internal/pubsub/pubsub.go#L63-L68
